// Chassis
#define BACK_LEFT_PORT 1
#define MID_LEFT_PORT 3
#define FRONT_LEFT_PORT 11
#define BACK_RIGHT_PORT 4
#define MID_RIGHT_PORT 5
#define FRONT_RIGHT_PORT 6

// Other
#define BACK_LIFT_PORT 12
#define FRONT_LIFT_PORT 20
#define BACK_PNEUMATIC_PORT 'B'
#define FRONT_PNEUMATIC_PORT 'A'
#define INERT_PORT 19
