#define BACK_LEFT_PORT 1
#define MID_LEFT_PORT 2
#define FRONT_LEFT_PORT 3
#define BACK_RIGHT_PORT 4
#define MID_RIGHT_PORT 5
#define FRONT_RIGHT_PORT 6

#define INERT_PORT 7

#define PNEUMATIC_PORT 'A'
